runtime: python
env: flex
service: nyc-price-prediction
entrypoint: gunicorn -b :$PORT main:app --timeout 500
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.12"
manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 4
liveness_check:
  path: "/liveness_check"